### ISSUE TITLE
RLocalStorage.clear() ?

### ISSUE THREAD

**Issue by mariafigueiredo** [simplyGits/reactive-local-storage#2]

**Comment by lieuwex** [comment]
Hey I have no idea why you closed this issue. But it's a good idea, no idea why I didn't add this, since there isn't a reason not to, guess I just forgot it. Anyway, in f84f983dd7504ab0b52059bd1b8f3f10115e3beb I have added a clear function, which has been published in `2.1.0`.

**Comment by mariafigueiredo** [comment]
Hi :) 
I closed this issue because when I use localStorage.clear(); all my localstorages have been cleaned. I checked and the RLocalStorage were cleaned too.

I changed  (again :D ) the name of the issue.

thanks for the answer!

**Comment by lieuwex** [comment]
> I use localStorage.clear(); all my localstorages have been cleaned

Ah yes that's true :)
However with that approach the dependencies won't be updated, so if you use `count()` you won't be notified that all items have been removed.

> I changed (again :D ) the name of the issue.

Thanks!
